theme:workflow:
  - ".github/**"

theme:build:
  - "gradle/**"
  - "build.gradle"
  - "build.gradle.kts"
  - "gradle.properties"
  - ".gitignore"

theme:core:
  - "src/main/java/**"
  - "src/main/kotlin/**"
  - "src/main/resources/**"

theme:tests:
  - "src/test/java/**"
  - "src/test/kotlin/**"
  - "src/test/resources/**"

