dist: trusty

language: java

addons:
  chrome: stable

jdk:
  - openjdk8

script:
  - ./gradlew clean test

before_install:
  - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc