name: Java CI with Gradle

on:
  push:
    branches: '*'
    #branches: [ master, api_test, ui_test, bug_fix ]
  pull_request:
    branches:
      - 'api_test'
      - 'ui_test'
      - 'bug_fix'
    #branches: [ master, api_test, ui_test, bug_fix ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #java: [ 8.0.192, 11.0.7 ] # Setup 2 parallel jobs on both java versions
        java: [ 11.0.7 ]

    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v1

      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build allureReport

      - uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./allure-report/
